name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - run: |
          python3 -m pip install uv
          uv sync --group dev

      - name: mypy
        run: uv run mypy --config-file pyproject.toml

      - name: bandit
        run: uv run bandit -r satel_ethm
